### PR TITLE
Try to automatically find runsettings if none are specified

### PR DESCRIPTION
**Pull request by OskiKervinen-MF**
Runsettings files need to be manually activated in Visual Studio. This activation cannot be shared with a team and is even wiped out if you remove the .vs directory from your working directory. This makes it hard to work in an environment where a .runsettings file needs to be active at all times to avoid running random executables.

This pull request solves the problem by automatically looking for *.runsettings files in the solution directory and above, similarly to the way git looks for a .gitignore. Any catch adapter settings in them are merged into one, with settings closer to the solution taking precedence (well, the only settings so far are lists, which are actually merged, but in principle.)

If a specific runsettings file is manually provided in Visual Studio, no such search is done. The rationale is that if you have some specific testing scenarios, we don't want to include random settings from generic files to them.

The implementation is based on the `IRunSettingsService` interface. Apparently Visual Studio can detect it and uses it to load settings for test runs. Unlike the `ISettingsProvider`, the service is called also when there is no runsettings file.

### CODE REVIEW

**Comment by xkbeyer** [comment]
Good work. There is only one drawback. Before if I don't want to use the settings, I removed it from the solution (but kept the file). Now it is always taken w/o really knowing it. I'm not sure it's a problem and how to deal with it.

**Comment by OskiKervinen-MF** [comment]
You could keep such optional setting files in a subdirectory under the solution directory. They would not be detected from there.

Or, if you feel the ability to keep such files in the root is essential, I could add an option like "IncludeAutomatically", that could be false by default. If it was false, the option file with it would not be taken into account automatically.

**Comment by xkbeyer** [comment]
Good work. There is only one drawback. Before if I don't want to use the settings, I removed it from the solution (but kept the file). Now it is always taken w/o really knowing it. I'm not sure it's a problem and how to deal with it.

**Comment by xkbeyer** [comment]
I think it is not essential to have it in the root directory.  It seems important to me that this behavior is described in the README.MD file.

**Comment by OskiKervinen-MF** [comment]
True. Done.

**Pull request merged**
