### PR TITLE
Measure time taken by each test

### PR DESCRIPTION
**Pull request by OskiKervinen-MF**
Used System.Diagnostics.Stopwatch, which should give very accurate results.

### CODE REVIEW

**Comment by xkbeyer** [comment]
That's something I've been thinking about. I'd take the time the test runner gives me. I think this refers to the execution time of the test.

**Comment by OskiKervinen-MF** [comment]
Yes, but the thing is, the test runner executes a new Windows process for each test. This time dominates the execution time for small focused tests, so I would prefer not hiding it from the user. The trivial tests in the Reference project all take around 100ms when run through VS, and essentially 0ms according to command line Catch.

This is relevant information to the user. It makes it clear that for truly massive test sets, it is best to run the whole from the command line and only smaller particularly interesting subsets from VS.

If the capability to execute multiple tests with a single execution were developed, it would of course be essential to switch to letting catch do the timing. The best approach I can see for that is using the `--input-file` parameter. Now that I think of it, that would be really good, but I cannot be sure I can find the time to look into it.

**Comment by xkbeyer** [comment]
Ok, I see. But therefor the VS shows the Total Run Time. However, the time
overhead is much more then the actual test run (in catch). So let me look
into the --input-file parameter. Let's see what the differences will be.

Update: I implemented (feab6864a23425840e6b0f95a8068d5201e4c79c) it. In that case the process start and run time takes only once into account.

**Comment by xkbeyer** [comment]
I think with the last commit it is implemented and the PR can be closed.

**Pull request closed without merging**
